name    'msopentech-windowsazure'
version '1.1.1'
source 'https://github.com/MSOpenTech/azure-puppet.git'
author 'msopentech'
summary 'Windows Azure cloud provisioning module'
description 'Windows Azure cloud provisioning module'
project_page 'https://github.com/MSOpenTech/azure-puppet'
