name 'msopentech-microsoftazure'
version '1.2.3'
source 'https://github.com/MSOpenTech/azure-puppet.git'
author 'msopentech'
summary 'Microsoft Azure cloud provisioning module'
description 'Microsoft Azure cloud provisioning module'
project_page 'https://github.com/MSOpenTech/azure-puppet'
